mysql: '127.0.0.1:3307:root:tu4ka:prison'
spawnLoc: 'world 1 1 1 1 1'
price:
  SANDSTONE-0: 0.35
  LEAVES: 0.00234375
  LOG_2-1: 0.02
  COAL: 0.046875
  SADDLE: 2.3
  GOLD_BLOCK: 1.0
  ENDER_STONE: 2.5
  QUARTZ: 0.125
  SAND: 0.0140625
  QUARTZ_BLOCK: 0.7
  SAPLING: 0.03125
  LOG: 0.35
  NAME_TAG: 2.0
  SEEDS: 0.01
  WOOL-11: 0.35
  WEB: 0.25
  FLINT: 0.1875
  LAPIS_BLOCK: 0.35
  PRISMARINE-0: 0.7
  PRISMARINE-1: 1.32
  PRISMARINE-2: 1.82
  DIAMOND_BLOCK: 5.0
  OBSIDIAN: 10.0
  QUARTZ_ORE: 0.1640625
  COBBLESTONE: 0.0234375
  STICK: 1.6
  RAW_FISH: 1.0
  SPIDER_EYE: 2.0
  SANDSTONE-2: 0.5
  SANDSTONE-1: 0.91
  GRAVEL: 0.0140625
  MELON: 0.01
  IRON_BLOCK: 0.5
  SOUL_SAND: 0.15625
  EMERALD: 0.3
  RAW_FISH-1: 0.26
  DIAMOND_ORE: 2.2
  WOOL-0: 0.4
  RAW_FISH-3: 0.55
  RAW_FISH-2: 1.5
  IRON_ORE: 0.09296875
  SAND-1: 0.02
  NETHERRACK: 0.0625
  STRING: 0.25
  GOLD_ORE: 0.1875
  COAL_BLOCK: 0.7
  STONE: 0.05453125
  RABBIT_HIDE: 1
  FEATHER: 0.55
  RED_SANDSTONE: 1.625
  DIRT: 0.0125
  RAW_FISH-0: 0.12
  BOWL: 0.9
  TRIPWIRE_HOOK: 0.9
  BONE: 0.9
  LEATHER: 0.95
  INK_SACK-0: 0.1
  INK_SACK-3: 0.33
  COAL_ORE: 0.078125
  EMERALD_ORE: 0.4
  DIAMOND: 1.0
  WOOL: 0.4
  EMERALD_BLOCK: 0.5
  BRICK: 0.06
  IRON_INGOT: 0.0
  IRON: 0.001
  IRONINGOT: 0.0
  BRICKS: 0.02
  WOOD: 0.2
  HAY_BLOCK: 0.05
  PUMPKIN: 0.03
  SNOW_BALL: 0.003
  PACKED_ICE: 0.2
  SNOW_BLOCK: 0.03
  REDSTONE_BLOCK: 1
  REDSTONE_ORE: 0.75
  REDSTONE: 0.088
  EYE_OF_ENDER: 0.0
  SPONGE: 0.2
  SPONGE_1: 0.25
  MYCEL: 0.8
  NOTE_BLOCK: 0.65
  STAINED_CLAY: 1.5
  STAINED_CLAY-7: 1.95
  STAINED_CLAY-12: 0.7
  STAINED_CLAY-15: 0.75
  MOSSY_COBBLESTONE: 1.25